### ISSUE TITLE
Category1 and Category2 sintaxys errors

### ISSUE THREAD

**Issue by JulioCCruzE** [BioRoboticsUNAM/SRGSConverter#1]
I found some errors in CategoryI and Catergory2 grammars.

1. The Converter generate the variable **$fllwhdst**, but that variable is a meta:
            $fllwhdst = {void meta: Follow {name1} to the {room 2}}.

2. In **follow** and **guide** rules appear the ruleref **#_pronobj**, however the rule name is **#_pronobjs**.

3. Finally, in **polite** rule at the start only appears:  **</item**>.

**Comment by kyordhel** [comment]
K. All these map to the class GrammarConverter, which is [this file](https://github.com/kyordhel/GPSRCmdGen/blob/f1d253e15953828204048c6657ec5539772cd306/CommandGenerator/GrammarConverter.cs) at the time of the issue. Therefore you won't see any changes reflected here.

### 1.
Noted.

### 2.
Noted.

### 3.
Looks like a big bug. This will take a little more time to fix.

**Comment by kyordhel** [comment]
Ready.

Number 1) and 2) have been fixed (cheap solution but still a fix). 
Regarding 3, I couldn't find the bug, so maybe it's also solved (collateral of others). Shall you find it again, please provide details on how to replicate it.
